infomont/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from infotor import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^infotor/', include('infotor.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'infotor.views.handler404'
handler500 = 'infotor.views.handler500'

infotor/urls.py
"Mappa gli url del sito"

from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import url
from infotor import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^mappa/$', views.mappa, name='mappa'),
    url(r'^forra/(?P<id_forra>[0-9]+)/$', views.mostra_forra, name='mostra_forra'),
    url(r'^forra/(?P<id_forra>[0-9]+)/modifica/$', views.modifica_forra, name='modifica_forra'),
]

# urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

handler404 = 'infotor.views.handler404'
handler500 = 'infotor.views.handler500'

infotor/models.py
from math import modf

from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from infotor.validators import frac_min_validator, timespan_validator

PUNTEGGI = ((1, 1), (2, 2), (3, 3), (4, 4))
LIVELLI = ((1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7))

class Forra(models.Model):

    id = models.IntegerField(verbose_name='Id Forra', db_column='NUME', primary_key=True)
    nome = models.CharField(verbose_name='Nome Forra', db_column='TREK1', max_length=80)
    id_percorso = models.IntegerField(verbose_name='Id Percorso', db_column='IDPERC') #models.ForeignKey('Percorso', verbose_name='Id Percorso', db_column='IDPERC')
    
    # TODO aggiungere i campi di collegamento che non mi sembrano tanto ok
    # id percorso
    # numero percorso
    # nome tratta

    grado_impegno = models.ForeignKey('GradoImpegno', verbose_name='Grado Impegno', db_column='IMPTOR', null=True, blank=True)

    verticalita = models.DecimalField(verbose_name='Livello Verticalità', db_column='LIVVER', choices=LIVELLI,
        max_digits=1, decimal_places=0, validators=[MinValueValidator(0), MaxValueValidator(len(LIVELLI))], null=True, blank=True)
    acquaticita = models.DecimalField(verbose_name='Livello Acquaticità', db_column='LIVH2O', choices=LIVELLI,
        max_digits=1, decimal_places=0, validators=[MinValueValidator(0), MaxValueValidator(len(LIVELLI))], null=True, blank=True)
    bellezza = models.DecimalField(verbose_name='Punteggio Bellezza', db_column='LIVBEL', choices=PUNTEGGI,
        max_digits=1, decimal_places=0, validators=[MinValueValidator(0), MaxValueValidator(len(PUNTEGGI))], null=True, blank=True)
    divertimento = models.DecimalField(verbose_name='Punteggio Divertimento', db_column='LIVDIV', choices=PUNTEGGI,
        max_digits=1, decimal_places=0, validators=[MinValueValidator(0), MaxValueValidator(len(PUNTEGGI))], null=True, blank=True)

    numero_calate = models.DecimalField(verbose_name='Numero Calate', db_column='NUMC',
        max_digits=1, decimal_places=0, validators=[MinValueValidator(0)], null=True, blank=True)
    calata_massima = models.DecimalField(verbose_name='Calata Massima (m)', db_column='CALMAX',
        max_digits=1, decimal_places=0, validators=[MinValueValidator(0)], null=True, blank=True)
    lunghezza_min_corda = models.DecimalField(verbose_name='Lunghezza minima corda singola (m)', db_column='CORMIN',
        max_digits=2, decimal_places=0, validators=[MinValueValidator(0)], null=True, blank=True)
    numero_min_corde = models.DecimalField(verbose_name='Numero minimo di corde', db_column='MINCORDE',
        max_digits=1, decimal_places=0, validators=[MinValueValidator(0)], null=True, blank=True)
    dislivello = models.DecimalField(verbose_name='Dislivello (m)', db_column='DISLIV',
        max_digits=2, decimal_places=0, null=True, blank=True)
    ampiezza_bacino = models.DecimalField(verbose_name='Ampiezza Bacino (km2)', db_column='AMPBAC',
        max_digits=4, decimal_places=0, validators=[MinValueValidator(0)], null=True, blank=True)

    origine_acqua = models.ForeignKey('OrigineAcqua', verbose_name='Origine Acqua', db_column='ORIGACQUA', null=True, blank=True)
    # TODO completare
    # quota partenza forra
    # quota arrivo forra
    
    "C'e' gia' un TEMPO_ANDATA e TEMPO_RITORNO nei campi presi da Percorso. Per adesso uso quelli."
    #ore_avvicinamento = models.DecimalField(verbose_name='Ore Avvicinamento', db_column='HAVV',
    #    max_digits=5, decimal_places=2, validators=[MinValueValidator(0), frac_min_validator], null=True, blank=True)
    ore_discesa = models.CharField(verbose_name='Ore Discesa', db_column='HCAL', max_length=5, validators=[timespan_validator], null=True, blank=True)
    #ore_rientro = models.DecimalField(verbose_name='Ore Rientro', db_column='HRIE',
    #    max_digits=5, decimal_places=2, validators=[MinValueValidator(0), frac_min_validator], null=True, blank=True)

    minuti_navetta = models.CharField(verbose_name='Tempo Navetta', validators=[timespan_validator], db_column='MMNAV', max_length=5, null=True, blank=True)
    km_navetta = models.DecimalField(verbose_name='Kilometri Navetta', db_column='KMNAV',
        max_digits=3, decimal_places=0, validators=[MinValueValidator(0)], null=True, blank=True)

    opere_idrauliche = models.ForeignKey('OperaIdraulica', verbose_name='Opere Idrauliche', db_column='OPEIDR', null=True, blank=True)
    litologia = models.ForeignKey('Litologia', verbose_name='Litologia', db_column='LITOL', null=True, blank=True)
    stagionalita = models.ManyToManyField('Mese', verbose_name='Mesi ok', db_column='STAGIONE', null=True, blank=True)

    # --- Checkpoints (foto) SONO FOREIGN KEY, c'è la tabella sotto
    checkpoint1 = models.ForeignKey('Checkpoint', verbose_name='Checkpoint 1', db_column='CHECKP1',
        related_name='checkpoint1', null=True, blank=True)
    checkpoint2 = models.ForeignKey('Checkpoint', verbose_name='Checkpoint 2', db_column='CHECKP2',
        related_name='checkpoint2', null=True, blank=True)

    # --- Informazioni (Memo / Testo libero) ---
    vincoli_ambientali = models.TextField(verbose_name='Vincoli ambientali', db_column='VINCOLI',
        max_length=250, null=True, blank=True)
    presentazione_forra = models.TextField(verbose_name='Presentazione forra', db_column='PRES',
        max_length=250, null=True, blank=True)
    descr_accesso_valle = models.TextField(verbose_name='Descrizione accesso a valle', db_column='DESACCV',
        max_length=250, null=True, blank=True)
    descr_accesso_monte = models.TextField(verbose_name='Descrizione accesso a monte', db_column='DESACCM',
        max_length=250, null=True, blank=True)
    descr_avvicinamento = models.TextField(verbose_name='Descrizione avvicinamento', db_column='DESAVV',
        max_length=250, null=True, blank=True)
    descr_percorso = models.TextField(verbose_name='Descrizione percorso', db_column='DESPERC',
        max_length=250, null=True, blank=True)
    descr_uscita = models.TextField(verbose_name='Descrizione uscita', db_column='DESUSC',
        max_length=250, null=True, blank=True)

    # --- Profilo forra ---
    profilo = models.ImageField(upload_to='profili/', verbose_name='Profilo Forra', db_column='PROFILO', 
        null=True, blank=True)
    note = models.TextField(verbose_name='Note', db_column='NOTE', max_length=250, null=True, blank=True)
    
    
    
    # ----------------- CAMPI COPIATI DA PERCORSO ---------------------------
    
    percorribilita = models.ForeignKey('Condizioni', verbose_name='Percorribilità', db_column='PERCORR', null=True, blank=True)
    descrizione = models.CharField(verbose_name='Descrizione', db_column='DENOMI', max_length=80, null=True, blank=True)

    lunghezza_piana = models.DecimalField(verbose_name='Lunghezza Piana (km)', db_column='PERLUN',
        max_digits=5, decimal_places=0, null=True, blank=True)
    lunghezza_inclinata = models.DecimalField(verbose_name='Lunghezza Inclinata (km)', db_column='PERLUNF',
        max_digits=5, decimal_places=0, null=True, blank=True)
    quota_inizio = models.DecimalField(verbose_name='Quota Inizio (slm)', db_column='PERQUO1',
        max_digits=4, decimal_places=0, null=True, blank=True)
    quota_fine = models.DecimalField(verbose_name='Quota Fine (slm)', db_column='PERQUO2',
        max_digits=4, decimal_places=0, null=True, blank=True)
    pendenza = models.DecimalField(verbose_name='Pendenza (%)', db_column='PENDENZA',
        max_digits=5, decimal_places=2, null=True, blank=True)
    tempo_andata = models.CharField(verbose_name='Tempo di percorrenza andata', db_column='PERTEM1', max_length=5, null=True, blank=True)
    tempo_ritorno = models.CharField(verbose_name='Tempo di percorrenza ritorno', db_column='PERTEM2', max_length=5, null=True, blank=True)
    difficolta = models.ForeignKey('Difficolta', verbose_name='Difficoltà', db_column='PERDIF', null=True, blank=True)
    segnaletica = models.ForeignKey('Segnaletica', verbose_name='Segnaletica', db_column='SEGNI', null=True, blank=True)
    data_aggiornamento = models.DateField(verbose_name='Data Aggiornamento', db_column='DATARIL', null=True, blank=True)
    # rete_regionale = models.ForeignKey('Rete', db_column='RETEREG', null=True) # TODO metti la tabella corrispondente
    codice_catasto = models.CharField(verbose_name='Codice Catasto Regionale', db_column='CODREG', max_length=12, null=True, blank=True)
    operatore = models.CharField(verbose_name='Ente Manutentore', db_column='OPERATORE', max_length=80, null=True, blank=True)
    #interesse_storico = models.ForeignKey('Valenza', db_column='STORICO', null=True) # TODO metti la tabella corrispondente
    #interesse_architettonico = models.ForeignKey('Valenza', db_column='ARCHITETT', null=True)
    #interesse_paesaggistico = models.ForeignKey('Valenza', db_column='PAESAGG', null=True)
    #interesse_naturalistco = models.ForeignKey('Valenza', db_column='NATURAL', null=True)
    link_CMS = models.CharField(verbose_name='Link CMS', db_column='LINK', max_length=16, null=True, blank=True)
    aggiornatore = models.CharField(verbose_name='Aggiornatore', db_column='UTENTE', max_length=16, null=True, blank=True)
    
    

    class Meta:
        verbose_name_plural = 'Forre'

    def __str__(self):
        return str(self.id)

    def save(self, *args, **kwargs):
        Forra._validate_range(self.verticalita, 1, len(LIVELLI))
        Forra._validate_range(self.acquaticita, 1, len(LIVELLI))
        Forra._validate_range(self.bellezza, 1, len(PUNTEGGI))
        Forra._validate_range(self.divertimento, 1, len(PUNTEGGI))
        Forra._validate_non_negative(self.numero_calate)
        Forra._validate_non_negative(self.calata_massima)
        Forra._validate_non_negative(self.lunghezza_min_corda)
        Forra._validate_non_negative(self.numero_min_corde)
        Forra._validate_non_negative(self.ampiezza_bacino)
        #Forra._validate_non_negative(self.minuti_navetta)

infotor/forms.py
from django import forms
from infotor.models import Forra, Checkpoint

class CheckpointForm(forms.ModelForm):
    
    class Meta:
        model = Checkpoint
        fields = [
            'immagine',
            'descrizione'
        ]
        

class ForraForm(forms.ModelForm):

    class Utils:
        "Contain static functions that can be called in the main class body"
        @staticmethod
        def generate_decimal_field(name, positive=True):
            field = Forra._meta.get_field(name)
            max_val = 10 ** (field.max_digits - field.decimal_places) - 1
            if positive:
                return forms.DecimalField(max_value=max_val, min_value=0, decimal_places=field.decimal_places, required=False)
            else:
                return forms.DecimalField(max_value=max_val, decimal_places=field.decimal_places, required=False)
          
        #@staticmethod      
        #def generate_time_field(name):
        #    field = Forra._meta.get_field(name)
            

    numero_calate = Utils.generate_decimal_field('numero_calate')
    calata_massima = Utils.generate_decimal_field('calata_massima')
    lunghezza_min_corda = Utils.generate_decimal_field('lunghezza_min_corda')
    numero_min_corde = Utils.generate_decimal_field('numero_min_corde')
    dislivello = Utils.generate_decimal_field('dislivello', False)
    ampiezza_bacino = Utils.generate_decimal_field('ampiezza_bacino')
    km_navetta = Utils.generate_decimal_field('km_navetta')
    
    #tempo_andata = Utils.generate_time_field('tempo_andata')
    #ore_discesa = Utils.generate_time_field('ore_discesa')
    #tempo_ritorno = Utils.generate_time_field('tempo_ritorno')
    #minuti_navetta = Utils.generate_time_field('minuti_navetta')
    
    #ore_avvicinamento = Utils.generate_decimal_field('tempo_andata')

    class Meta:
        model = Forra
        fields = [
            'id',
            'nome',
            'grado_impegno',
            'verticalita',
            'acquaticita',
            'bellezza',
            'divertimento',
            'numero_calate',
            'calata_massima',
            'lunghezza_min_corda',
            'numero_min_corde',
            'dislivello',
            'ampiezza_bacino',
            'origine_acqua',
            'tempo_andata', #'ore_avvicinamento',
            'ore_discesa',
            'tempo_ritorno', #'ore_rientro',
            'minuti_navetta',
            'km_navetta',
            'opere_idrauliche',
            'litologia',
            'stagionalita',
            'checkpoint1',
            'checkpoint2',
            'vincoli_ambientali',
            'presentazione_forra',
            'descr_accesso_monte',
            'descr_accesso_valle',
            'descr_avvicinamento',
            'descr_percorso',
            'descr_uscita',
            'profilo',
            'note',
        ]

        widgets = {
            'stagionalita': forms.CheckboxSelectMultiple,
        }
    
    def clean_tempo_andata(self):
        return self.clean_minutes(self.cleaned_data['tempo_andata'])
    def clean_ore_discesa(self):
        return self.clean_minutes(self.cleaned_data['ore_discesa'])
    def clean_tempo_ritorno(self):
        return self.clean_minutes(self.cleaned_data['tempo_ritorno'])
    def clean_minuti_navetta(self):
        return self.clean_minutes(self.cleaned_data['minuti_navetta'])
    
    def clean_minutes(self, value_to_clean):
        if value_to_clean is None:
            return None
        #try:
        hours, minutes = value_to_clean.split(":")
        if len(hours) > 2 or len(hours) < 1:
            return None
        else:
            if len(hours) == 1:
                hours = "0{}".format(hours)
        if len(minutes) > 2 or len(minutes) < 1:
            return None
        else:
            if len(minutes) == 1:
                minutes = "{}0".format(minutes)
        return "{}:{}".format(hours, minutes)
        #except:
        #    return None
        return None

templates/infotor/base.html
<!doctype html>
{% load staticfiles %}
{% load infotor_template_tags %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Icon -->
    <link rel="icon" href="{% static "images/favicon.png" %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <!-- Font Awesome Icon Library -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <!-- Dashboard custom CSS -->
    <link rel="stylesheet" href="{% static "dashboard.css"%}">
    {% block links %}
    {% endblock %}
    <title>
      Infotor
    </title>
  </head>
  <body>
    {% block navbar %}
      {% render_navbar %}
    {% endblock %}

    {% block main %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

templates/infotor/choice.html
{% if field %}
<div class="form-group">
    <label for="{{ field.name }} ">Example select</label>
    <select class="form-control" id="{{ field.name }}">
      {% if choices %}
        {% for choice in choices %}
            {% if choice.selected %}
                <option selected>{{ choice.name }}</option>
            {% else %}
                <option>{{ choice.name }}</option>
            {% endif %}
        {% endfor %}
      {% endif %}
    </select>
  </div>
{% else %}
<p>Errore: Campo mancante!</p>
{% endif %}

templates/infotor/editable.html
{% if field %}
<div class="form-group">
  <label for="{{ field.name }}">{{ field.name }}</label>
  <input type="text" class="form-control" id="{{ field.name }}" placeholder="{{ field.data }}">
</div>
{% else %}
<p>Errore: Campo mancante!</p>
{% endif %}

templates/infotor/mappa.html
{% extends 'infotor/base.html' %}
{% load infotor_template_tags %}
{% load static %}

{% block main %}
<div class="container-fluid">
  <div class="row">

    {% render_sidebar %}

    <main role="main" class="col-md-10 ml-auto col-lg-10 px-4" style="padding-top:70px">
      
      <iframe style="width:80vw; height:90vh;" frameBorder="0" allowfullscreen src="https://umap.openstreetmap.fr/en/map/torrenti_304838?scaleControl=false&miniMap=false&scrollWheelZoom=false&zoomControl=true&allowEdit=false&moreControl=true&searchControl=null&tilelayersControl=null&embedControl=null&datalayersControl=true&onLoadPanel=undefined&captionBar=false&datalayers=803429%2C803483#11/46.6268/511930.7309"></iframe>
       
    </main>
    
  </div>
</div>
{% endblock %}

templates/infotor/modifica_forra.html
{% extends 'infotor/base.html' %}
{% load infotor_template_tags %}
{% load staticfiles %}
{% load bootstrap4 %}
{% load i18n %}

{% block links %}
<link rel="stylesheet" href="{% static "forra.css"%}">
{% endblock %}

{% block scripts %}
<script src="{% static "forra.js" %}"></script>
<script>
  // Sovrascrive il numero di righe di default di righe nel campi descrittivi
  $(document).ready(function(){
    $("textarea").attr({
      "rows": "3",
    });

    $(".checkbox").addClass("form-check form-check-inline");
    $(".has-error").addClass("is-invalid");

  });
</script>
{% endblock %}

{% block main %}
<div class="container-fluid">
  {% render_sidebar_forra %}
  <main role="main" class="col-md-10 ml-sm-auto col-lg-10 px-4" style="padding-top:70px">
    {#% if form %#}
      {% if form.errors %}
        {% bootstrap_alert "Controllare che tutti i campi siano corretti" alert_type="danger"%}
        {{ form.errors }}
      {% endif %}
    {% language 'it' %}
    <form action="." method="POST" id="ForraForm" onsubmit="return confirm('Salvare la Forra?')" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-row">
        <div class="col-md-5">
            {% bootstrap_field form.nome label_class='h5' form_group_class='pb-0'%}
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-2">
            <div class="pb-0">
                <label class="h5" for="id_id">Id Forra</label>
                <input type="number" name="id" value="{{ forra.id }}" class="form-control" title="" required="" id="id_id" readonly>
            </div>
        </div>
         <div class="col-md-2">
            <div class="pb-0">
                <label class="h5" for="id_percorso">Id Percorso</label>
                <input type="number" name="id_percorso" value="{{ forra.id_percorso }}" class="form-control" title="" required="" id="id_percorso" readonly>
            </div>
        </div>
        <div class="ml-auto">
          <button class="btn btn-success btn-sm ml-auto" type="submit">
              <i class="fas fa-save fa-fw"></i>
          </button>
          <a class="btn btn-danger btn-sm ml-auto"
            {% if forra %}
            href="/infotor/forra/{{ forra.id }}"
            {% else %}
            href="/infotor/"
            {% endif %}
            onclick="return confirm('Annullare le modifiche e uscire?')">
            <i class="fas fa-times fa-fw"></i>
          </a>
        </div>

        <!-- TODO Completare-->
      </div>
      <hr>
      <div class="row section" id="Dati">
        <div class="col-md-12">
          {% bootstrap_field form.stagionalita label_class='h6'%}
        </div>
        <div class="col-md-5 px-3">
          {% bootstrap_field form.verticalita layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
          {% bootstrap_field form.acquaticita layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
          {% bootstrap_field form.bellezza layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>"  %}
          {% bootstrap_field form.divertimento layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
          <br>
          {% bootstrap_field form.tempo_andata layout='horizontal' size='small' form_group_class='pb-0' placeholder='hh:mm' addon_after="<div class='col-md-1'>h</div>" %}
          {% bootstrap_field form.ore_discesa layout='horizontal' size='small' form_group_class='pb-0' placeholder='hh:mm' addon_after="<div class='col-md-1'>h</div>" %}
          {% bootstrap_field form.tempo_ritorno layout='horizontal' size='small' form_group_class='pb-0' placeholder='hh:mm' addon_after="<div class='col-md-1'>h</div>" %}
          {% bootstrap_field form.minuti_navetta layout='horizontal' size='small' form_group_class='pb-0' placeholder='hh:mm' addon_after="<div class='col-md-1'>h</div>" %}
          {% bootstrap_field form.km_navetta layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'>km</div>" %}
        </div>
        <div class="col-md-5 px-3">
          {% bootstrap_field form.grado_impegno layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
          {% bootstrap_field form.numero_calate layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
          {% bootstrap_field form.calata_massima layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'>m</div>" %}
          {% bootstrap_field form.lunghezza_min_corda layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'>m</div>" %}
          {% bootstrap_field form.numero_min_corde layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
          <br>
          {% bootstrap_field form.dislivello layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'>m</div>"  %}
          {% bootstrap_field form.ampiezza_bacino layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'>km2</div>" %}
          {% bootstrap_field form.origine_acqua layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
          {% bootstrap_field form.opere_idrauliche layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
          {% bootstrap_field form.litologia layout='horizontal' size='small' form_group_class='pb-0' addon_after="<div class='col-md-1'> </div>" %}
        </div>
      </div>

      <div class="row section" id="Checkpoints">
        <div class="form-group col-md-8">
            {% bootstrap_field checkpoint1_form.immagine label_class='h6' %}
            {% bootstrap_field checkpoint1_form.descrizione label_class='h6' %}
            {% bootstrap_field checkpoint2_form.immagine label_class='h6' %}
            {% bootstrap_field checkpoint2_form.descrizione label_class='h6' %}
        </div>
      </div>

      <div class="row section" id="Informazioni">
        <div class="form-group col-md-5 px-3">
          {% bootstrap_field form.presentazione_forra label_class='h6' %}
          {% bootstrap_field form.descr_accesso_valle label_class='h6' %}
          {% bootstrap_field form.descr_avvicinamento label_class='h6' %}
          {% bootstrap_field form.descr_uscita label_class='h6' %}
        </div>
        <div class="form-group col-md-5 px-3">
          {% bootstrap_field form.vincoli_ambientali label_class='h6' %}
          {% bootstrap_field form.descr_accesso_monte label_class='h6' %}
          {% bootstrap_field form.descr_percorso label_class='h6' %}
        </div>
      </div>

      <div class="row section" id="Profilo">
        <div class="form-group col-md-8">
          {% bootstrap_field form.profilo label_class='h6' %}
          {% bootstrap_field form.note label_class='h6' %}
        </div>
      </div>
    </form>
    {% endlanguage %}
    {#% else %#}
    <!--h2>Errore: form mancante!</h2-->
    {#% endif %#}
  </main>
</div>
{% endblock %}

templates/infotor/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap py-1 px-0 shadow">
  <a class="navbar-brand mx-3" href="/">
    <img src="{% static "images/logo.png" %}" height="40" alt="">
  </a>
  <!-- BEGIN Navbar sections and links -->
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
      <a class="nav-link text-light" href="/">UnicoCAI Torrentismo</a>
    </li>
  </ul>
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <a class="nav-link text-light" href="#">
        <i class="fas fa-sign-out-alt"></i>
        <span>Logout</span>
      </a>
    </li>
  </ul>
  <!-- END Navbar sections and links -->
</nav>